### ISSUE TITLE
Need Help with ‘Load More’ Button Behavior in BuddyX Theme with BuddyPress

### ISSUE THREAD

**Issue by podporujeme** [vapvarun/buddyx#12]
I am using the BuddyX theme with BuddyPress. On the page that displays all activities, when I click the “Load More” button, more posts are loaded as expected, but the page automatically scrolls down. This behavior is different on the group activity page, where clicking the “Load More” button loads more posts without the page scrolling down.

This automatic scrolling is not user-friendly, especially on mobile devices, because when new posts are loaded, users have to scroll up to see them, which is counter-intuitive. I would like the “Load More” button on the all activities page to behave the same way as it does on the group activity page, i.e., load more posts without the page scrolling down.

I have tried to modify the PHP and JavaScript code to change this behavior, but so far have not been successful. Am looking for help from other developers to solve this problem.

**Comment by vapvarun** [comment]
it's fixed in today's release

**Comment by podporujeme** [comment]
> it's fixed in today's release

still bug

**Comment by podporujeme** [comment]
@vapvarun Here is video https://www.youtube.com/watch?v=1bYYoZUU660 In first part you can see homepage activity page, in second part u can see group page. Do you see diference????
