### ISSUE TITLE
"This XML file does not appear to have any style information associated with it."

### ISSUE THREAD

**Issue by LiamBirt** [vapvarun/buddyx#5]
I installed BuddyPress, bbPress and BuddyX main theme and child theme on my WordPress website. I use NGINX, Php7.4-fpm, MySQL and AWS (EC2, Route 53, ASG, ELB etc.). 

When I click on the RSS feed button, it takes me to a website that shows the backend code and says:

"This XML file does not appear to have any style information associated with it. The document tree is shown below."

<rss xmlns:content="http://purl.org/rss/1.0/modules/content/" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:sy="http://purl.org/rss/1.0/modules/syndication/" xmlns:slash="http://purl.org/rss/1.0/modules/slash/" version="2.0">
<channel>
<title>MedSupply Network | Site-Wide Activity</title>
<link>https://www.medsupplynetwork.com/activity/</link>
<atom:link href="https://www.medsupplynetwork.com/activity/feed/" rel="self" type="application/rss+xml"/>
<description>Activity feed for the entire site.</description>
<lastBuildDate>Sun, 16 May 2021 18:22:22 +0000</lastBuildDate>
<generator>https://buddypress.org/?v=7.3.0</generator>
<language>en-US</language>
<ttl>30</ttl>
<sy:updatePeriod>hourly</sy:updatePeriod>
<sy:updateFrequency>2</sy:updateFrequency>
</channel>
</rss>

**Comment by vapvarun** [comment]
that's a raw RSS feed and BuddyPress default you can install feed reader extension in your browsers.
