### ISSUE TITLE
Header Background color remains white

### ISSUE THREAD

**Issue by Kervadecg** [vapvarun/buddyx#8]
Hello,
I have set a specific color to the Header background color and it was working well.
Recently, this color has switched to White. I tried to reset a different color but my customisation is not taken into account. The color remains white.
This issue may have appeared after an update of BuddyX ?
Thanks for your support.

Link : to the site :  https://3amu.com/

**Comment by vapvarun** [comment]
Please make sure you are using Kirki v3.1.9
